body:
  - type: markdown
    attributes:
      value: |
        ## 💬 What's your question?

        <details>
          <summary><em>Need some pointers on crafting your question?</em></summary>

          <br>

          1. **Start succinctly:** Jump to the point with a concise question.
          2. **Conciseness matters:** Keep it brief yet specific; avoid lengthy explanations.
          3. **Include code:** Attach relevant code snippets, configurations, and errors.
          4. **Add screenshots:** If applicable, provide screenshots.
        </details>

  - type: textarea
    id: improvements
    attributes:
      label: Question
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

        > **🚀 Try _Priority Support_!**
        >
        > If you're in a pinch, don't hesitate to take advantage of my [_Priority Support_ service](https://github.com/sponsors/privatenumber) where you can ask me questions in an exclusive forum. I'm well equppied to assist you with this project and would be happy to help you out! 🙂
