name: 🐛 Bug report
description: Run into a bug? File a report and get the help you need!
labels: [bug, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        💁‍♂️ This is a collaborative effort. Please do your best to debug, communicate, and demonstrate the problem.

        ## 👀 Tell us about the bug
        A _clear and concise_ description of what the bug is.

  - type: textarea
    attributes:
      label: Problem
      description: Please refrain from describing anything other than the problem.
      placeholder: |
        What's the problem?
        Do you have an error stack trace?
        Do you have screenshots?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: |
        What did you expect to happen?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📋 Show us the bug

        > [!CAUTION]
        > Without proving the bug is in this project via *minimal* reproduction, your issue will be closed without response.

        The minimal reproduction is the core of your issue. This is usually all we read.

        The first thing we'll do is scrutinize every code, file, and dependency to see how they impact the bug. If you can delete it and still produce the bug, it's not needed.

        Upload your reproduction to [StackBlitz](https://stackblitz.com) or a GitHub repository and use GitHub Actions to show the error.

        Please do your best to _show_ the bug rather than talking about it. This will lead to a speedy resolution.

  - type: input
    attributes:
      label: Minimal reproduction URL
      placeholder: https://github.com/...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > **🙋 Need help?**
        >
        > Get personalized help through my [_Priority Support_ service](https://github.com/sponsors/privatenumber).
        > From minimal reproduction creation to debugging, I'm happy to assist you!

  - type: markdown
    attributes:
      value: "## 🌍 Environment"

  - type: input
    attributes:
      label: Version
      placeholder: v0.0.0
    validations:
      required: true

  - type: input
    attributes:
      label: Node.js version
      placeholder: v0.0.0
    validations:
      required: true

  - type: dropdown
    id: package-manager
    attributes:
      label: Package manager
      options:
        - npm
        - yarn
        - pnpm
        - bun
        - N/A
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating system
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🛠️ Contribute

  - type: checkboxes
    attributes:
      label: Bugs are expected to be fixed by those affected by it
      options:
        - label: I'm interested in working on this issue

  - type: checkboxes
    attributes:
      label: Compensating engineering work financially will speed up resolution
      options:
        - label: I'm willing to offer financial support

  - type: markdown
    attributes:
      value: |
        ## 🚀 Need immediate attention?
        Escalate this issue by becoming a [_Priority Patron_ sponsor](https://github.com/sponsors/privatenumber)! As a _Priority Patron_, your concern will receive prompt attention, ensuring faster and more efficient resolution.

        [👉 Become a _Priority Patron_ now!](https://github.com/sponsors/privatenumber)
